### ISSUE TITLE
WARNING: gp_event_queue.c:event_put():157: Event queue full, dropping event.

### ISSUE THREAD

**Issue by richiejp** [gfxprim/gppdf#2]
This happens loading a larger PDF. One with lots of images and is about 9.8MB.

The PDF displays fine after a brief pause where I assume it is being loaded.

**Comment by metan-ucw** [comment]
I guess that I found the problem at:

https://github.com/gfxprim/gfxprim/blob/master/libs/backends/gp_x11.c#L174

We do poll X11 events in a loop, process them and for some of them (key presses, mouse movement, etc.) we add them to the gfxprim queue. The gfxprim queue can hold up to 32 events, which means that if enough events accumulate on the X server side while the application renders a PDF page we get more events than the queue can handle.

I guess that we should stop processing events if the queue is full and return to the application so that the events can be processed to make room in the event queue.

**Comment by metan-ucw** [comment]
Should be fixed by:
https://github.com/gfxprim/gfxprim/commit/b0c96ae63e9e64607f2ae2bceb61c4282ea565bb
https://github.com/gfxprim/gfxprim/commit/f2fd0b958b265874f1727484c2cccf96212cd885

Please reopen if you see the warning even after these fixes.
